# Davis/Wu piecewise PV inversion (F77 tutorial code), gfortran build.
#
# Three grid variants are built from the same pristine sources in src/:
#
#   reg10  : original tutorial grid  NW/NL=10, NY=21, NX=45,
#            PR = 1000,850,700,500,400,300,250,200,150,100 hPa
#            -> pvpialln10, qinvert10, qinvertp10
#            (used only for regression against the shipped tutorial outputs)
#   inner9 : CESM wu9 levels        NW/NL=9,  NY=21, NX=45,
#            PR = 1000,850,700,500,400,300,250,200,100 hPa (150 dropped)
#            -> pvpialln_i, qinvert_i, qinvertp_i
#   outer9 : same levels, larger outer domain  NY=25, NX=89
#            -> pvpialln_o, qinvert_o, qinvertp_o
#
# In addition, SIZES lists extra 9-level window geometries (same PR table
# as inner9/outer9; only PARAMETER NY/NX differ) named by their grid:
# pvpialln_17x33, qinvert_17x33, ... (NY=17, NX=33).  These serve the
# boundary-condition robustness matrix (alternate inner/outer windows).
#
# The 9-level variants are generated by sed into build/gen/ (sources stay
# pristine).  The sed edits touch exactly:
#   - the PARAMETER lines  (NW=10 / NL=10 -> 9; outer9 also NY=21->25,
#     NX=45->89; parameters are repeated in each program AND subroutine,
#     sed replaces every occurrence, which is required for consistency),
#   - the one active (tab-indented) DATA PR/ .../ statement per file.
# All other level-dependent constants (PIB/PIT, DPI=500./FLOAT(NL), BB/BH/BL,
# array bounds) are written in terms of NW/NL and self-adjust.

FC      = gfortran
FFLAGS  = -O2 -std=legacy -w

SRC     = src
GEN     = build/gen
BIN     = build

SED9    = -e 's/NW=10/NW=9/' -e 's/NL=10/NL=9/' \
          -e 's|^\tDATA PR/.*|\tDATA PR/ 1.0, 0.85, 0.7, 0.5, 0.4, 0.3, 0.25, 0.2, 0.1/|'
SEDOUT  = -e 's/NY=21/NY=25/' -e 's/NX=45/NX=89/'

BINS10  = $(BIN)/pvpialln10 $(BIN)/qinvert10 $(BIN)/qinvertp10
BINSI   = $(BIN)/pvpialln_i $(BIN)/qinvert_i $(BIN)/qinvertp_i
BINSO   = $(BIN)/pvpialln_o $(BIN)/qinvert_o $(BIN)/qinvertp_o

# extra 9-level NYxNX window geometries (see header comment)
SIZES   = 17x33 25x113 17x45 21x89
BINSSZ  = $(foreach s,$(SIZES),\
            $(BIN)/pvpialln_$(s) $(BIN)/qinvert_$(s) $(BIN)/qinvertp_$(s))

all: $(BINS10) $(BINSI) $(BINSO) $(BINSSZ)

# ---------------- reg10: compile pristine sources -------------------
$(BIN)/pvpialln10: $(SRC)/pvpialln_94UV.f
	@mkdir -p $(BIN)
	$(FC) $(FFLAGS) -o $@ $<

$(BIN)/qinvert10: $(SRC)/qinvert21_94.f
	@mkdir -p $(BIN)
	$(FC) $(FFLAGS) -o $@ $<

$(BIN)/qinvertp10: $(SRC)/qinvertp21_94.f
	@mkdir -p $(BIN)
	$(FC) $(FFLAGS) -o $@ $<

# ---------------- inner9: 9 levels, 45 x 21 -------------------------
$(GEN)/pvpialln_i.f: $(SRC)/pvpialln_94UV.f
	@mkdir -p $(GEN)
	sed $(SED9) $< > $@
	@grep -q 'NW=9' $@ && grep -q '0.2, 0.1/' $@

$(GEN)/qinvert_i.f: $(SRC)/qinvert21_94.f
	@mkdir -p $(GEN)
	sed $(SED9) $< > $@
	@grep -q 'NL=9' $@ && grep -q '0.2, 0.1/' $@

$(GEN)/qinvertp_i.f: $(SRC)/qinvertp21_94.f
	@mkdir -p $(GEN)
	sed $(SED9) $< > $@
	@grep -q 'NL=9' $@ && grep -q '0.2, 0.1/' $@

# ---------------- outer9: 9 levels, 89 x 25 -------------------------
$(GEN)/pvpialln_o.f: $(SRC)/pvpialln_94UV.f
	@mkdir -p $(GEN)
	sed $(SED9) $(SEDOUT) $< > $@
	@grep -q 'NW=9' $@ && grep -q 'NY=25' $@ && grep -q 'NX=89' $@

$(GEN)/qinvert_o.f: $(SRC)/qinvert21_94.f
	@mkdir -p $(GEN)
	sed $(SED9) $(SEDOUT) $< > $@
	@grep -q 'NL=9' $@ && grep -q 'NY=25' $@ && grep -q 'NX=89' $@

$(GEN)/qinvertp_o.f: $(SRC)/qinvertp21_94.f
	@mkdir -p $(GEN)
	sed $(SED9) $(SEDOUT) $< > $@
	@grep -q 'NL=9' $@ && grep -q 'NY=25' $@ && grep -q 'NX=89' $@

$(BIN)/%_i: $(GEN)/%_i.f
	$(FC) $(FFLAGS) -o $@ $<

$(BIN)/%_o: $(GEN)/%_o.f
	$(FC) $(FFLAGS) -o $@ $<

# ---------------- SIZES: 9 levels, NY x NX taken from the suffix ----
# $(call size-rules,<NYxNX>,<NY>,<NX>) emits the sed-generation and
# compile rules for one geometry, following the inner9/outer9 pattern
# (SED9 level edits plus PARAMETER NY/NX replacement in every program
# unit; main and subroutine dimensions must agree).
define size-rules
$(GEN)/pvpialln_$(1).f: $(SRC)/pvpialln_94UV.f
	@mkdir -p $(GEN)
	sed $(SED9) -e 's/NY=21/NY=$(2)/' -e 's/NX=45/NX=$(3)/' $$< > $$@
	@grep -q 'NW=9' $$@ && grep -q 'NY=$(2)' $$@ && grep -q 'NX=$(3)' $$@

$(GEN)/qinvert_$(1).f: $(SRC)/qinvert21_94.f
	@mkdir -p $(GEN)
	sed $(SED9) -e 's/NY=21/NY=$(2)/' -e 's/NX=45/NX=$(3)/' $$< > $$@
	@grep -q 'NL=9' $$@ && grep -q 'NY=$(2)' $$@ && grep -q 'NX=$(3)' $$@

$(GEN)/qinvertp_$(1).f: $(SRC)/qinvertp21_94.f
	@mkdir -p $(GEN)
	sed $(SED9) -e 's/NY=21/NY=$(2)/' -e 's/NX=45/NX=$(3)/' $$< > $$@
	@grep -q 'NL=9' $$@ && grep -q 'NY=$(2)' $$@ && grep -q 'NX=$(3)' $$@

$(BIN)/pvpialln_$(1): $(GEN)/pvpialln_$(1).f
	$(FC) $(FFLAGS) -o $$@ $$<

$(BIN)/qinvert_$(1): $(GEN)/qinvert_$(1).f
	$(FC) $(FFLAGS) -o $$@ $$<

$(BIN)/qinvertp_$(1): $(GEN)/qinvertp_$(1).f
	$(FC) $(FFLAGS) -o $$@ $$<
endef

$(foreach s,$(SIZES),$(eval $(call size-rules,$(s),$(word 1,$(subst x, ,$(s))),$(word 2,$(subst x, ,$(s))))))

clean:
	rm -f $(BINS10) $(BINSI) $(BINSO) $(BINSSZ) $(GEN)/*.f

.PHONY: all clean
